person:
  name: Neo
  age: 21
server:
  port: 8084
spring:
  profiles:
    active: dev
---

server:
  port: 8082
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student?serverTimezone=UTC
    username: root
    password: admin
  thymeleaf:
    prefix: classpath:/public/
    suffix: .html
    cache: false


mybatis:
  #mybatis mapper文件的位置
  mapper-locations: classpath*:mapper/**/*.xml
  #扫描pojo类的位置,在此处指明扫描实体类的包，在mapper中就可以不用写pojo类的全路径名了
  type-aliases-package: com.echart.demo.domain

---
server:
  port: 8083
spring:
  profiles: test